;;; cl-lib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from cl-lib.el

 (let ((d (file-name-directory #$)))
  (when (member d load-path)
    (setq load-path (append (remove d load-path) (list d)))))

;;; End of scraped data

(provide 'cl-lib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cl-lib-autoloads.el ends here
