;;; org-evil-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-evil-commands.el

(register-definition-prefixes "org-evil-commands" '("org-evil-heading-"))


;;; Generated autoloads from org-evil-core.el

(register-definition-prefixes "org-evil-core" '("org-evil-"))


;;; Generated autoloads from org-evil-list.el

(register-definition-prefixes "org-evil-list" '("org-evil-list-"))


;;; Generated autoloads from org-evil-motion.el

(register-definition-prefixes "org-evil-motion" '("org-evil-"))


;;; Generated autoloads from org-evil-table.el

(register-definition-prefixes "org-evil-table" '("org-evil-table-"))

;;; End of scraped data

(provide 'org-evil-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-evil-autoloads.el ends here
