;;; helm-evil-markers-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-evil-markers.el

(autoload 'helm-evil-markers "helm-evil-markers" "\
List evil markers with helm." t)
(autoload 'helm-evil-markers-set "helm-evil-markers" "\
Wrapper to set marker denoted by CHAR to position POS and update markers.
If ADVANCE is t, the marker advances when inserting text at it; otherwise,
it stays behind.

(fn CHAR &optional POS ADVANCE)" t)
(autoload 'helm-evil-markers-toggle "helm-evil-markers" "\
Enable or disable helm-evil-markers keybindings." t)
(register-definition-prefixes "helm-evil-markers" '("helm-evil-markers-"))

;;; End of scraped data

(provide 'helm-evil-markers-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-evil-markers-autoloads.el ends here
