;;; helm-icons-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from helm-icons.el

(autoload 'helm-icons-enable "helm-icons" "\
Enable `helm-icons'." t)
(register-definition-prefixes "helm-icons" '("helm-icons-"))

;;; End of scraped data

(provide 'helm-icons-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-icons-autoloads.el ends here
